// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXe7PYp3wEroXRw6dYi9_99zLYTmweYts',
    appId: '1:428964772556:web:f2e52836c56d5b5e76e069',
    messagingSenderId: '428964772556',
    projectId: 'evoverse-a055b',
    authDomain: 'evoverse-a055b.firebaseapp.com',
    storageBucket: 'evoverse-a055b.appspot.com',
    measurementId: 'G-7L4C5DF12Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl8r9IhF9r5oInp_ZcB4mpTBmkRYOU2ts',
    appId: '1:428964772556:android:731155d824acee7076e069',
    messagingSenderId: '428964772556',
    projectId: 'evoverse-a055b',
    storageBucket: 'evoverse-a055b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA795GVeP15Da6n5Z5xYoft7nxxAfdS55Q',
    appId: '1:428964772556:ios:19d8d2fa9fd0658276e069',
    messagingSenderId: '428964772556',
    projectId: 'evoverse-a055b',
    storageBucket: 'evoverse-a055b.appspot.com',
    iosClientId: '428964772556-ij2fs0fcv9ilm7pjd3cgnbrcpik30q0j.apps.googleusercontent.com',
    iosBundleId: 'app.evoverse',
  );
}
